{{- if .Values.config.secrets }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "#app#-xxx.name" . }}
    chart: {{ template "#app#-xxx.chart" . }}
    component: "{{ template "#app#-xxx.name" . }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "#app#-xxx.fullname" . }}-senv
  annotations:
    checksum/secrets: {{ tpl (toYaml .Values.config.secrets) . | sha256sum }}
data:
  {{- range $key, $value := .Values.config.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
