---
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  DD_SECRET_VAULT: 'br-devops-kv'
  BEDROCK_DEPLOYMENT_CATALOG: 'br_deployments.yaml'
  BEDROCK_CLUSTER: 'BR_Prod'
  BEDROCK_INVOKED_DIR: ''
  BEDROCK_SUBSCRIPTION: 'br-prod-az-service-connection'

jobs:
  - job: 'br_update_prod_environment'
    timeoutInMinutes: 120
    steps:
      - checkout: self
        # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
        persistCredentials: true
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Init Bedrock Tools Container Runtime'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            ./.bedrock/ci/recipes/init_bedrock_tools.sh
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Static Analysis'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            sast_repo
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Provision CI k8s cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            deploy_cluster
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Deploy Dashboard to Cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            deploy_dashboard_to_cluster
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Deploy Datadog to Cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            deploy_datadog_to_cluster
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Deploy Neuvector to Cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            deploy_neuvector_to_cluster
