---
#
# trigger this pipeline when any service dependency is updated
#
# notes:
# the happy path for working triggers when service dependencies are updated is very narrow
# and does not match available microsoft documentation at the time of this writing
#
# the most important undocumented fact is that this YAML must be on the default branch
# ** FOR EACH PIPELINE THAT REFERENCES THIS YAML **
# the setting is well hidden in the webUI under:
# pipelines->{pipeline}->{...}->edit->{...}->triggers->yaml->getsources->default_Branch_for_manual_and_scheduled_builds
#
# note also, the runner pool can be changed at
# pipelines->{pipeline}->{...}->edit->{...}->triggers->yaml->pipeline
#
# you can test if your default branch is correct by inspecting the default branch shown in:
# pipelines->{pipeline}->{...}->run
#
# see also:
# https://github.com/MicrosoftDocs/azure-devops-docs/issues/8435#issuecomment-633257995
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example#resources-pipelines
# https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml
#

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: 'br-http-https-echo'
      source: 'brock-k8s-svc-http-https-echo'
      trigger:
        branches:
          include:
            - 'bedrock-main'
            - 'master-bedrock'
    - pipeline: 'br-oauth-proxy-docker'
      source: 'brock-k8s-svc-oauth2-proxy'
      trigger:
        branches:
          include:
            - 'bedrock-main'
            - 'master-bedrock'
    - pipeline: 'br-tls-certificate-manager-svc-docker'
      source: 'brock-k8s-svc-tls_certificate_manager'
      trigger:
        branches:
          include:
            - 'bedrock-main'
            - 'master-bedrock'
    - pipeline: 'platform-api-addressvalidation-svc'
      source: 'platform-api-addressvalidation'
      trigger:
        branches:
          include:
            - 'bedrock-main'
            - 'master-bedrock'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
    persistCredentials: true
  - task: Docker@2
    displayName: Login to ACR for Dev registry
    inputs:
      command: login
      containerRegistry: br-dev-acr-service-connection
  - task: AzureCLI@2
    displayName: 'Install tools if needed'
    inputs:
      azureSubscription: 'br-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/install_tools_if_needed.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Trace Environment'
    inputs:
      azureSubscription: 'br-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/trace_environment.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Static Analysis'
    inputs:
      azureSubscription: 'br-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './recipes/sast_shellcheck.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Update Service Dependencies'
    inputs:
      azureSubscription: 'br-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/update_service_dependencies.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
