# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- deployment_request/qa

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
    persistCredentials: true
  - task: Docker@2
    displayName: Login to ACR for Dev registry
    inputs:
      command: login
      containerRegistry: cf-dev-acr-service-connection
  - task: Docker@2
    displayName: Login to ACR for QA registry
    inputs:
      command: login
      containerRegistry: cf-qa-acr-service-connection
  - task: AzureCLI@2
    displayName: 'Install tools if needed'
    inputs:
      azureSubscription: 'cf-qa-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/install_tools_if_needed.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Trace Environment'
    inputs:
      azureSubscription: 'cf-qa-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/trace_environment.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Static Analysis'
    inputs:
      azureSubscription: 'cf-qa-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './recipes/sast_shellcheck.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Check Key Vault Access'
    inputs:
      azureSubscription: 'cf-qa-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/check_qa_key_vault_access.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Promote Deployed Dev Artifacts to QA'
    inputs:
      azureSubscription: 'cf-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/promote_dev_to_qa_k8s.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Push packaged Artifacts to QA'
    inputs:
      azureSubscription: 'cf-qa-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/publish_packaged_chart_to_qa.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit'))
    displayName: 'Install latest umbrella chart to development k8s cluster'
    inputs:
      azureSubscription: 'cf-qa-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/deploy_umbrella_chart_to_qa.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE