---
#
# trigger this pipeline when any service dependency is updated
#
# notes:
# the happy path for working triggers when service dependencies are updated is very narrow
# and does not match available microsoft documentation at the time of this writing
#
# the most important undocumented fact is that this YAML must be on the default branch
# ** FOR EACH PIPELINE THAT REFERENCES THIS YAML **
# the setting is well hidden in the webUI under:
# pipelines->{pipeline}->{...}->edit->{...}->triggers->yaml->getsources->default_Branch_for_manual_and_scheduled_builds
#
# note also, the runner pool can be changed at
# pipelines->{pipeline}->{...}->edit->{...}->triggers->yaml->pipeline
#
# you can test if your default branch is correct by inspecting the default branch shown in:
# pipelines->{pipeline}->{...}->run
#
# see also:
# https://github.com/MicrosoftDocs/azure-devops-docs/issues/8435#issuecomment-633257995
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example#resources-pipelines
# https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/pipeline-triggers.md
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml
#

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: 'cf-admin-web-api-docker'
      source: 'cf_admin_web_api'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-atrius-objects-api-docker'
      source: 'cf_atrius_objects'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-authz-web-api-docker'
      source: 'cf_authz_web_api'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-elm-web-api-docker'
      source: 'cf_elm_web_api'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-http-https-echo'
      source: 'cf_http_https_echo'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-network-view-web-api-docker'
      source: 'cf_network_view_web_api'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-oauth-proxy-docker'
      source: 'cf_oauth2_proxy'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-react-app-docker'
      source: 'cf_react_app'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-self-healing-api-docker'
      source: 'cf_self_healing_lights'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-self-healing-app-docker'
      source: 'cf_self_healing_react_app'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-assets-v2-telemetry-svc-docker'
      source: 'cf_assets_v2_telemetry'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-smoketest-svc-docker'
      source: 'cf_smoketest'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-tls-certificate-manager-svc-docker'
      source: 'cf_tls_certificate_manager'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-city-state-zip-svc-docker'
      source: 'cf_city_state_zip'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-coordinate-transforms-svc-docker'
      source: 'cf_coordinate_transforms'
      trigger:
        branches:
          include:
            - 'master-bytelight'
    - pipeline: 'cf-ecy-ingest-svc-docker'
      source: 'cf_ecy_ingest'
      trigger:
        branches:
          include:
            - 'master-bytelight'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
    persistCredentials: true
  - task: Docker@2
    displayName: Login to ACR for Dev registry
    inputs:
      command: login
      containerRegistry: cf-dev-acr-service-connection
  - task: AzureCLI@2
    displayName: 'Install tools if needed'
    inputs:
      azureSubscription: 'cf-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/install_tools_if_needed.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Trace Environment'
    inputs:
      azureSubscription: 'cf-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/trace_environment.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Static Analysis'
    inputs:
      azureSubscription: 'cf-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './recipes/sast_shellcheck.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
  - task: AzureCLI@2
    displayName: 'Update Service Dependencies'
    inputs:
      azureSubscription: 'cf-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/update_service_dependencies.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
