#
# trigger this pipeline when any service dependency is updated
#

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: 'cf_atrius_objects'
      source: 'cf_atrius_objects'
      trigger:
        branches:
          include:
          - master-bytelight

foobar:
  exit:
    - pipeline: 'cf_admin_web_api'
      project: 'ByteLight'
      source: '/cf/services/cf_admin_web_api'
      branch: 'master-bytelight'
      trigger:
        branches:
          include:
            - 'refs/tags/r*'
            - 'master-bytelight'
    - pipeline: 'xx-cf_atrius_objects'
      source: 'cf\services\cf_atrius_objects'
      branch: 'master-bytelight'
      trigger:
        branches:
          include:
            - 'refs/tags/r*'
            - 'master-bytelight'
    - pipeline: 'cf_authz_web_api'
      project: 'ByteLight'
      source: '/cf/services/cf_authz_web_api'
      branch: 'master-bytelight'
    - pipeline: 'cf_elm_web_api'
      project: 'ByteLight'
      source: '/cf/services/cf_elm_web_api'
      branch: 'master-bytelight'
    - pipeline: 'cf_http_https_echo'
      project: 'ByteLight'
      source: '/cf/services/cf_http_https_echo'
      branch: 'master-bytelight'
    - pipeline: 'cf_network_view_web_api'
      project: 'ByteLight'
      source: '/cf/services/cf_network_view_web_api'
      branch: 'master-bytelight'
    - pipeline: 'cf_oauth2_proxy'
      project: 'ByteLight'
      source: '/cf/services/cf_oauth2_proxy'
      branch: 'master-bytelight'
    - pipeline: 'cf_react_app'
      project: 'ByteLight'
      source: '/cf/services/cf_react_app'
      branch: 'master-bytelight'
    - pipeline: 'cf_self_healing_lights'
      project: 'ByteLight'
      source: '/cf/services/cf_self_healing_lights'
      branch: 'master-bytelight'
    - pipeline: 'cf_self_healing_react_app'
      project: 'ByteLight'
      source: '/cf/services/cf_self_healing_react_app'
      branch: 'master-bytelight'
  containers:
    - container: 'cf_atrius_objects'
      type: 'ACR'
      azureSubscription: 'cf-dev-acr-service-connection'
      resourceGroup: 'Acr-CfDev'
      registry: 'cfdevregistry'
      repository: 'cf_atrius_objects'
      trigger:
        tags:
          include:
            - 'refs/tags/r*'
          exclude:
            - 'regs/tags/r0*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
    persistCredentials: true
  - task: Docker@2
    condition: and(succeeded(), ne(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit'))
    displayName: Login to ACR for Dev registry
    inputs:
      command: login
      containerRegistry: cf-dev-acr-service-connection
  - task: AzureCLI@2
    condition: and(succeeded(), ne(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit'))
    displayName: 'Update Service Dependencies'
    inputs:
      azureSubscription: 'cf-dev-az-service-connection'
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: './ci/recipes/update_service_dependencies.sh'
      # inlineScript:
      # arguments
      # powerShellErrorActionPreference
      # addSpnToEnvironment
      # useGlobalConfig
      # workingDirectory
      # failOnStandardError
      # powerShellIgnoreLASTEXITCODE
