apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "cf-network-view-web-api-docker.fullname" . }}-schema-migration'
  labels:
    {{- include "cf-network-view-web-api-docker.labels" . | nindent 4 }}
spec:
  backoffLimit: 5
  # activeDeadlineSeconds: 100
  template:
    spec:
      containers:
        - name: '{{ .Chart.Name }}'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: STATSD_PORT
              value: "8125"
          envFrom:
            - configMapRef:
                name: '{{ template "cf-network-view-web-api-docker.fullname" . }}-env'
            - secretRef:
                name: '{{ template "cf-network-view-web-api-docker.fullname" . }}-senv'
          command:
            - '/assets/run_ruby_migrations.sh'
      restartPolicy: OnFailure
