@startuml
autonumber

Actor Asset_Tags_2_0 #lightblue
Participant Edgar
Participant ECY1000
Participant Azure_IOT_Hub
Participant Azure_IOT_Custom_Endpoints
Participant Azure_IOT_Internal_EH_Endpoint
Participant Atrius_Service_Fabric
Database Atrius_Avro
Participant CF_Real_Time_Asset_V2_Telemetry_EH #lightblue
Participant CF_Real_Time_Asset_V2_Ingest_Service #lightblue
Participant CF_EH_AssetsV1_endpoint_EH_contract #lightblue
Participant AssetV1_stream_EventHub #pink
Participant AssetV1_data_archive_account #pink
Participant StreamAnalytics #lightgreen

== Asset Tags 2.0 - going forward - June 2020 ===

Asset_Tags_2_0 -> Edgar: tag_telemetry
Edgar -> ECY1000: tag_telemetry, edgar_status
ECY1000 -> Azure_IOT_Hub : positionArray_v2, statusArray_v2, edgarStatusArray_v2
Azure_IOT_Hub -> Azure_IOT_Custom_Endpoints : filter(AvroCapture)
Azure_IOT_Custom_Endpoints -> Atrius_Avro : data blobs
Azure_IOT_Hub -> Azure_IOT_Custom_Endpoints : filter(LuminaireDiagnostics)
Azure_IOT_Custom_Endpoints -> Azure_IOT_Custom_Endpoints : Event Hub(st = 'cls' or mt = 'edgarStatusArray' or mt = 'lumUpdate' or mt = 'heartbeat')
Azure_IOT_Hub -> Azure_IOT_Custom_Endpoints : filter(ScheduledCallRoute)
Azure_IOT_Custom_Endpoints -> Azure_IOT_Custom_Endpoints : new for Relay API
Azure_IOT_Hub -> Azure_IOT_Custom_Endpoints : filter(KeepSendingToDefaultEndpoint)
Azure_IOT_Custom_Endpoints -> Azure_IOT_Internal_EH_Endpoint : IOT_Internal(st != 'cls' and mt != 'edgarStatusArray' and mt != 'lumUpdate' and mt != 'heartbeat' and st != 'cr' and mt != 'scheduledCall')
Azure_IOT_Internal_EH_Endpoint -> Atrius_Service_Fabric
Azure_IOT_Hub -> Azure_IOT_Custom_Endpoints #lightblue : filter(CF_Real_Time_Asset_V2_Ingest_Service)
Azure_IOT_Custom_Endpoints -> CF_Real_Time_Asset_V2_Telemetry_EH :  positionArray_v2, statusArray_v2, edgarStatusArray_v2
CF_Real_Time_Asset_V2_Telemetry_EH -> CF_Real_Time_Asset_V2_Ingest_Service : positionArray_v2, statusArray_v2, edgarStatusArray_v2
CF_Real_Time_Asset_V2_Telemetry_EH -> CF_Real_Time_Asset_V2_Telemetry_EH : AvroCapture
CF_Real_Time_Asset_V2_Ingest_Service -> CF_EH_AssetsV1_endpoint_EH_contract : positionArray_v1, statusArray_v1, edgarStatusArray_v1
CF_EH_AssetsV1_endpoint_EH_contract -> AssetV1_stream_EventHub : positionArray_v1, statusArray_v1, edgarStatusArray_v1
AssetV1_stream_EventHub -> AssetV1_data_archive_account : Avro(positionArray_v1, statusArray_v1, edgarStatusArray_v1)
AssetV1_stream_EventHub -> StreamAnalytics : positionArray_v1, statusArray_v1, edgarStatusArray_v1

@enduml
