@startuml

Collections Deployments
Collections Environments
Collections AZ_Key_Vaults

Control Extractor
Control AZ_CLI

Boundary IaaS
Boundary PaaS

Control Helm
Boundary SaaS

Deployments -> Extractor
Environments -> Extractor

Extractor -> AZ_CLI : yamlConfig
AZ_CLI -> IaaS : \n\
  ResourceGroups, KeyVaults, \n\
  Public_IP, LoadBalancer, \n\
  VirtualMachines, K8SCluster \n\
  StorageAccounts

AZ_CLI -> PaaS : \n\
  database, kafka, \n\
  containerRegistry, \n\

AZ_Key_Vaults -> Extractor : Keys, ConnectionStrings
Extractor -> Helm : yamlConfig
Helm -> SaaS

@enduml