---
deployments:
  - name: 'CF_Development'
    iaas:
      provider:
        azure:
          enabled: 'true'
          subscription:
            name: 'ConnectedFacilities-Dev'
            id: '5649ad97-1fd3-460f-b569-9995bbb6c5c0'  # Acuity Brands, Inc. ConnectedFacilities-Dev
          location: 'eastus'
          tls_subscription:
            name: 'ConnectedFacilities-Dev'
            id: '5649ad97-1fd3-460f-b569-9995bbb6c5c0'  # Acuity Brands, Inc. ConnectedFacilities-Dev
          dns_subscription:
            name: 'Allspice-Dev'
            id: '5e49f516-d005-4ae8-a287-031c8573401c'  # Acuity Brands, Inc. Allspice-Dev
    external_services:
      atrius:
        databases:
          - db_host_name: 'pltdata01sqlsep2ftp3b7r'
            db_name: 'allspice-mapmanager01db'
            reader_name: 'CF_Reader'
            secret_name: 'ALLSPICEDEV-CFReader-SQLUserPassword'
        passage:
          ad_tenant: 'caadbe96-024e-4f67-82ec-fb28ff53d16d'  # Acuity Brands, Inc.
          authn_tenant: 'common'  # allow all AD tenants to authenticate
          api_host: 'passage.atrius-dev.acuitynext.io'
          api_application_id: '24b765b5-8108-4374-8141-1a65c0fc42ab'  # Acuity Brands Atrius Passage API
    k8s:
      namespace: 'cfk8s'
      context: 'cf-dev-k8s-001-admin'
      tls_secret_name: 'wildcarddevatrius-iotcom'
      pv_secret_namespace: 'br-pv'
    paas:
      dashboard:
        enabled: 'true'
        namespace: 'dashboard'
        port: 8001
      datadog:
        enabled: 'true'
        namespace: 'datadog'
      neuvector:
        enabled: 'true'
        namespace: 'neuvector'
        values:
          cve:
            updater:
              enabled: 'true'
          registry: 'cfdevregistry.azurecr.io'
    environment:
      app: 'cf'
      name: 'dev'
      config: './configuration/environments/cf_k8s_dev.yaml'
    helm:
      migration_timeout: '15m'
      umbrella:
        registry:
          name: 'cfdevregistry'
        name: 'cf-deployment-umbrella'
        version: '^9.0.0-0'
        deployment_name: 'cfk8s'
        values_file: ''
      storage:
        account:
          name: cfdevcmsa001abl
  - name: 'CF_CI'
    iaas:
      provider:
        azure:
          enabled: 'true'
          subscription:
            name: 'ConnectedFacilities-Dev'
            id: '5649ad97-1fd3-460f-b569-9995bbb6c5c0'  # Acuity Brands, Inc. ConnectedFacilities-Dev
          location: 'eastus'
          tls_subscription:
            name: 'ConnectedFacilities-Dev'
            id: '5649ad97-1fd3-460f-b569-9995bbb6c5c0'  # Acuity Brands, Inc. ConnectedFacilities-Dev
          dns_subscription:
            name: 'Allspice-Dev'
            id: '5e49f516-d005-4ae8-a287-031c8573401c'  # Acuity Brands, Inc. Allspice-Dev
    external_services:
      atrius:
        databases:
          - db_host_name: 'pltdata01sqlsep2ftp3b7r'
            db_name: 'allspice-mapmanager01db'
            reader_name: 'CF_Reader'
            secret_name: 'ALLSPICEDEV-CFReader-SQLUserPassword'
        passage:
          ad_tenant: 'caadbe96-024e-4f67-82ec-fb28ff53d16d'  # Acuity Brands, Inc.
          authn_tenant: 'common'  # allow all AD tenants to authenticate
          api_host: 'passage.atrius-dev.acuitynext.io'
          api_application_id: '24b765b5-8108-4374-8141-1a65c0fc42ab'  # Acuity Brands Atrius Passage API
    k8s:
      namespace: 'cfk8s'
      context: 'cf-ci-k8s-001-admin'
      tls_secret_name: 'wildcarddevatrius-iotcom'
      pv_secret_namespace: 'br-pv'
    paas:
      dashboard:
        enabled: 'true'
        namespace: 'dashboard'
        port: 8002
      datadog:
        enabled: 'false'
        namespace: 'datadog'
      neuvector:
        enabled: 'false'
        namespace: 'neuvector'
        values:
          cve:
            updater:
              enabled: 'true'
          registry: 'cfdevregistry.azurecr.io'
    environment:
      app: 'cf'
      name: 'ci'
      config: './configuration/environments/cf_k8s_ci.yaml'
    helm:
      migration_timeout: '10m'
      umbrella:
        registry:
          name: 'cfciregistry'
        name: 'cf-deployment-umbrella'
        deployment_name: 'cfk8s'
        version: '^9.0.0-0'
        values_file: ''
      storage:
        account:
          name: cfcicmsa001abl
  - name: 'CF_QA'
    iaas:
      provider:
        azure:
          enabled: 'true'
          subscription:
            name: 'ConnectedFacilities-QA'
            id: '781c62dc-1612-43e6-a0ca-a8138888691f'  # Acuity Brands, Inc. ConnectedFacilities-QA
          location: 'eastus'
          tls_subscription:
            name: 'ConnectedFacilities-QA'
            id: '781c62dc-1612-43e6-a0ca-a8138888691f'  # Acuity Brands, Inc. ConnectedFacilities-QA
          dns_subscription:
            name: 'Allspice-QA'
            id: 'a98f27b5-367a-44b6-af72-26fab4efc5f7'  # Acuity Brands, Inc. Allspice-QA
    external_services:
      atrius:
        databases:
          - db_host_name: 'pltdata01sqlsw3pyftzuvb'
            db_name: 'allspice-mapmanager01db'
            reader_name: 'CF_Reader'
            secret_name: 'ASPQA01US-CFReader-SQLUserPassword'
        passage:
          ad_tenant: 'caadbe96-024e-4f67-82ec-fb28ff53d16d'  # Acuity Brands, Inc.
          authn_tenant: 'common'  # allow all AD tenants to authenticate
          api_host: 'passage.atrius-qa.acuitynext.io'
          api_application_id: '528307d1-f67d-4dff-a3a8-c68dace2b072'  # Acuity Brands Atrius QA Passage API
    k8s:
      namespace: 'cfk8s'
      context: 'cf-qa-k8s-001-admin'
      tls_secret_name: 'wildcardqaatrius-iotcom'
      pv_secret_namespace: 'br-pv'
    paas:
      dashboard:
        enabled: 'true'
        namespace: 'dashboard'
        port: 8003
      datadog:
        enabled: 'true'
        namespace: 'datadog'
      neuvector:
        enabled: 'true'
        namespace: 'neuvector'
        values:
          cve:
            updater:
              enabled: 'true'
          registry: 'cfqaregistry.azurecr.io'
    environment:
      app: 'cf'
      name: 'qa'
      config: './configuration/environments/cf_k8s_qa.yaml'
    helm:
      migration_timeout: '15m'
      umbrella:
        registry:
          name: 'cfqaregistry'
        name: 'cf-deployment-umbrella'
        deployment_name: 'cfk8s'
        version: '^9.0.0-0'
        values_file: ''
      storage:
        account:
          name: cfqacmsa001abl
  - name: 'CF_Prod'
    iaas:
      provider:
        azure:
          enabled: 'true'
          subscription:
            name: 'ConnectedFacilities-Prod'
            id: 'e331d580-f48b-45d5-85c0-166dc80f3ed3'  # Acuity Brands, Inc. ConnectedFacilities-Prod
          location: 'eastus'
          tls_subscription:
            name: 'ConnectedFacilities-Prod'
            id: 'e331d580-f48b-45d5-85c0-166dc80f3ed3'  # Acuity Brands, Inc. ConnectedFacilities-Prod
          dns_subscription:
            name: 'Allspice-Dev'
            id: '5e49f516-d005-4ae8-a287-031c8573401c'  # Acuity Brands, Inc. Allspice-Dev
    external_services:
      atrius:
        databases:
          - db_host_name: 'pltdata01sqls5vysxyq75v'
            db_name: 'allspice-mapmanager01db'
            reader_name: 'CF_Reader'
            secret_name: 'ATRDEMO01US-CFReader-SQLUserPassword'
          - db_host_name: 'pltdata01sqlsbb6ahiz252'
            db_name: 'allspice-mapmanager01db'
            reader_name: 'CF_Reader'
            secret_name: 'ATRPROD02US-CFReader-SQLUserPassword'
        passage:
          ad_tenant: 'caadbe96-024e-4f67-82ec-fb28ff53d16d'  # Acuity Brands, Inc.
          authn_tenant: 'common'  # allow all AD tenants to authenticate
          api_host: 'passage.atrius-us.acuitynext.io'
          api_application_id: 'd9253624-7e87-426c-8132-75858e1dcf0b'  # Acuity Brands Atrius US Passage API
    k8s:
      namespace: 'cfk8s'
      context: 'cf-prod-k8s-001-admin'
      tls_secret_name: 'wildcarddevatrius-iotcom'
      pv_secret_namespace: 'br-pv'
    paas:
      dashboard:
        enabled: 'true'
        namespace: 'dashboard'
        port: 8004
      datadog:
        enabled: 'true'
        namespace: 'datadog'
      neuvector:
        enabled: 'true'
        namespace: 'neuvector'
        values:
          cve:
            updater:
              enabled: 'true'
          registry: 'cfprodregistry.azurecr.io'
    environment:
      app: 'cf'
      name: 'prod'
      config: './configuration/environments/cf_k8s_prod.yaml'
    helm:
      migration_timeout: '4h'
      umbrella:
        registry:
          name: 'cfprodregistry'
        name: 'cf-deployment-umbrella'
        deployment_name: 'cfk8s'
        version: '^9.0.0-0'
        values_file: ''
      storage:
        account:
          name: cfprodcmsa001abl
  - name: 'CF_Local'
    iaas:
      provider:
        docker-desktop:
          enabled: 'true'
    external_services:
      atrius:
        databases:
          - db_host_name: 'pltdata01sqlsep2ftp3b7r'
            db_name: 'allspice-mapmanager01db'
            reader_name: 'CF_Reader'
            secret_name: 'ALLSPICEDEV-CFReader-SQLUserPassword'
        passage:
          ad_tenant: 'caadbe96-024e-4f67-82ec-fb28ff53d16d'  # Acuity Brands, Inc.
          authn_tenant: 'common'  # allow all AD tenants to authenticate
          api_host: 'passage.atrius-dev.acuitynext.io'
          api_application_id: '24b765b5-8108-4374-8141-1a65c0fc42ab'  # Acuity Brands Atrius Passage API
    k8s:
      namespace: 'cfk8s'
      context: 'docker-desktop'
      tls_secret_name: 'wildcarddevatrius-iotcom'
      pv_secret_namespace: 'br-pv'
    paas:
      dashboard:
        enabled: 'true'
        namespace: 'dashboard'
        port: 8005
      datadog:
        enabled: 'false'
        namespace: 'datadog'
      neuvector:
        enabled: 'false'
        namespace: 'neuvector'
        values:
          cve:
            updater:
              enabled: 'true'
          registry: 'cfdevregistry.azurecr.io'
    environment:
      app: 'cf'
      name: 'local'
      config: './configuration/environments/cf_k8s_local.yaml'
    helm:
      migration_timeout: '5m'
      umbrella:
        registry:
          name: 'cfdevregistry'
        name: 'cf-deployment-umbrella'
        deployment_name: 'cfk8s'
        version: '^9.0.0-0'
        values_file: ''
      storage:
        account:
          name: cfdevcmsa001abl
  - name: 'GITLAB'
    iaas:
      provider:
        azure:
          enabled: 'true'
          subscription:
            name: 'ConnectedFacilities-Dev'
            id: '5649ad97-1fd3-460f-b569-9995bbb6c5c0'  # Acuity Brands, Inc. ConnectedFacilities-Dev
          location: 'eastus'
          dns_subscription:
            name: 'Allspice-Dev'
            id: '5e49f516-d005-4ae8-a287-031c8573401c'  # Acuity Brands, Inc. Allspice-Dev
    external_services:
      active_directory:
    k8s:
      namespace: 'gitlab'
      context: 'gitlab-001-k8s-admin'
      pv_secret_namespace: 'gl-pv'
    paas:
      dashboard:
        enabled: 'true'
        namespace: 'dashboard'
        port: 8006
      datadog:
        enabled: 'true'
        namespace: 'datadog'
        values:
          agents:
            containers:
              agent:
                env:
                  - name: DD_KUBELET_TLS_VERIFY
                    value: "false"
              processAgent:
                env:
                  - name: DD_KUBELET_TLS_VERIFY
                    value: "false"
              systemProbe:
                env:
                  - name: DD_KUBELET_TLS_VERIFY
                    value: "false"
              traceAgent:
                env:
                  - name: DD_KUBELET_TLS_VERIFY
                    value: "false"
            rbac:
              create: true
          clusterAgent:
            rbac:
              create: true
          clusterChecksRunner:
            env:
              - name: DD_KUBELET_TLS_VERIFY
                value: "false"
            rbac:
              create: true
          datadog:
            apiKey: d46cef3ec0ae9d0501ad1e852d6fee58
            clusterAgent:
              clusterAgent:
                metricsProvider:
                  enabled: true
              enabled: true
            clusterChecks:
              enabled: false
            collectEvents: true
            dogstatsd:
              nonLocalTraffic: true
              port: 8125
              useHostPort: true
            env:
              - name: DD_KUBELET_TLS_VERIFY
                value: "false"
            kubeStateMetricsEnabled: true
            leaderElection: true
            logs:
              containerCollectAll: true
              containerCollectUsingFiles: false
              enabled: true
          kube-state-metrics:
            collectors:
              verticalpodautoscalers: null
            rbac:
              create: true
      neuvector:
        enabled: 'true'
        namespace: 'neuvector'
        values:
          cve:
            updater:
              enabled: 'true'
          registry: 'acuitygitlabregistry.azurecr.io'
    environment:
      app: 'gitlab'
      name: '001'
      config: './configuration/environments/acuity_gitlab_001_k8s.yaml'
    helm:
      migration_timeout: '30m'
      umbrella:
        registry:
          name: 'gitlab'
          url: 'https://charts.gitlab.io/'
        name: 'gitlab'
        deployment_name: 'gitlab001'
        version: '^4.4.3-0'
        values_file: ''
      storage:
        account:
          name: ablgitlab001sa
---
