---
#
# trigger this pipeline when desired to perform a full CI test
#

trigger: none
pr: none

schedules:
  - cron: "0 4 * * *"
    displayName: Nightly build
    branches:
      include:
        - bedrock-main
    always: true

pool:
  vmImage: 'ubuntu-18.04'

variables:
  DD_SECRET_VAULT: 'br-devops-kv'
  BEDROCK_DEPLOYMENT_CATALOG: 'br_deployments.yaml'
  BEDROCK_CLUSTER: 'BR_CI'
  BEDROCK_INVOKED_DIR: ''
  BEDROCK_SUBSCRIPTION: 'br-dev-az-service-connection'

jobs:
  - job: 'br_ci_full_test'
    timeoutInMinutes: 120
    steps:
      - checkout: self
        condition: true
        # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
        persistCredentials: true
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Init Bedrock Tools Container Runtime'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            ./.bedrock/ci/recipes/init_bedrock_tools.sh
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Static Analysis'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            sast_repo
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Provision CI k8s cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            deploy_cluster
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Copy Deployed Dev Artifacts to CI'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            copy_upstream_to_cluster_k8s
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Push packaged Artifacts to CI'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            publish_packaged_chart_for_cluster
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Install latest umbrella chart to development k8s cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            deploy_umbrella_chart_to_cluster
      - task: AzureCLI@2
        condition: succeeded()
        displayName: 'Purge CI k8s cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            purge_cluster
