---
#
# trigger this pipeline when there is an update to the umbrella helm chart
#

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: 'deploy-umbrella-chart-to-dev'
      source: 'update_umbrella_chart'
      trigger:
        branches:
          include:
            - 'bedrock-main'
            - 'azure-pipelines'

pool:
  vmImage: 'ubuntu-18.04'

variables:
  DD_SECRET_VAULT: 'br-devops-kv'
  BEDROCK_DEPLOYMENT_CATALOG: 'br_deployments.yaml'
  BEDROCK_CLUSTER: 'BR_Development'
  BEDROCK_INVOKED_DIR: ''
  BEDROCK_SUBSCRIPTION: 'br-dev-az-service-connection'

jobs:
  - job: 'deploy_chart_to_dev_cluster'
    timeoutInMinutes: 120
    steps:
      - checkout: self
        condition: eq(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit')
        # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
        persistCredentials: true
      - task: AzureCLI@2
        condition: and( succeeded(), eq(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit') )
        displayName: 'Init Bedrock Tools Container Runtime'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            ./.bedrock/ci/recipes/init_bedrock_tools.sh
      - task: AzureCLI@2
        condition: and( succeeded(), eq(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit') )
        displayName: 'Static Analysis'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            sast_repo
      - task: AzureCLI@2
        condition: and( succeeded(), eq(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit') )
        displayName: 'Install latest umbrella chart to development k8s cluster'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_SECRET_VAULT=$(DD_SECRET_VAULT)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./.bedrock/ci/recipes/invoke_bedrock_recipe.sh
            deploy_umbrella_chart_to_cluster
