---
#
# trigger this pipeline when there is a commit to the bedrock-main branch
#

trigger:
  - bedrock-main
  - azure-pipelines

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  DD_CLIENT_API_KEY: ''
  DD_CLIENT_APP_KEY: ''
  BEDROCK_DEPLOYMENT_CATALOG: 'br_deployments.yaml'
  BEDROCK_CLUSTER: 'BR_Development'
  BEDROCK_INVOKED_DIR: ''
  BEDROCK_SUBSCRIPTION: 'br-dev-az-service-connection'

jobs:
  - job: 'update_helm_chart'
    timeoutInMinutes: 120
    steps:
      - checkout: self
        # readme: https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml
        persistCredentials: true
      - task: AzureCLI@2
        condition: and(succeeded(), ne(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit'))
        displayName: 'Init Bedrock Tools Container Runtime'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            ./ci/recipes/init_bedrock_tools.sh
      - task: AzureCLI@2
        condition: and(succeeded(), ne(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit'))
        displayName: 'Static Analysis'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_CLIENT_API_KEY=$(DD_CLIENT_API_KEY)
            DD_CLIENT_APP_KEY=$(DD_CLIENT_APP_KEY)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./ci/recipes/invoke_bedrock_recipe.sh
            sast_shellcheck
      - task: AzureCLI@2
        condition: and(succeeded(), ne(variables['Build.SourceVersionMessage'], 'automated update of semver on git commit'))
        displayName: 'Update Umbrella Chart semver'
        inputs:
          azureSubscription: $(BEDROCK_SUBSCRIPTION)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: >-
            DD_CLIENT_API_KEY=$(DD_CLIENT_API_KEY)
            DD_CLIENT_APP_KEY=$(DD_CLIENT_APP_KEY)
            BEDROCK_DEPLOYMENT_CATALOG=$(BEDROCK_DEPLOYMENT_CATALOG)
            BEDROCK_CLUSTER=$(BEDROCK_CLUSTER)
            BEDROCK_INVOKED_DIR=$(BEDROCK_INVOKED_DIR)
            ./ci/recipes/invoke_bedrock_recipe.sh
            update_helm_chart
