apiVersion: v2
name: 'br-deployment-umbrella'
description: 'BR: Umbrella for all BR services'
keywords:
  - 'bedrock'
  - 'umbrella'
type: application
home: ''  # The URL of this projects home page (optional)
sources: []  # A list of URLs to source code for this project (optional)
maintainers:
  - name: 'Paul Charlton'
    email: 'techguru@byiq.com'
    url: 'https://www.gitlab.com/techguru'
icon: ''
deprecated: false

dependencies: # A list of the chart requirements (optional)
  - name: 'br-http-https-echo'
    version: '^1.0.0-0'
    repository: '@brdevregistry'
    condition: 'br-http-https-echo.enabled'
    tags:
      - 'br-dev-debug'
    enabled: true
    import-values: [] # (optional)
    alias: 'br-http-https-echo'
  - name: 'br-oauth-proxy-docker'
    version: '^1.0.0-0'
    repository: '@brdevregistry'
    condition: 'br-oauth-proxy-docker.enabled'
    tags:
      - 'br-oauth-authn-service'
    enabled: true
    import-values: [] # (optional)
    alias: 'br-oauth-proxy-docker'
  - name: 'nginx-ingress'
    version: '1.41.2'
    repository: 'https://charts.helm.sh/stable'
    condition: 'br-waf-ingress.enabled'
    tags:
      - 'br-waf-ingress'
    enabled: true
    import-values: [] # (optional)
    alias: 'br-waf-ingress'
  - name: 'br-tls-certificate-manager-svc-docker'
    version: '^1.0.0-0'
    repository: '@brdevregistry'
    condition: 'br-tls-certificate-manager-svc-docker.enabled'
    tags:
      - 'br-tls-certificate-manager-svc-docker'
    enabled: true
    import-values: [] # (optional)
    alias: 'br-tls-certificate-manager-svc-docker'
  - name: 'platform-api-addressvalidation-svc'
    version: '^0.3.0-0'
    repository: '@brdevregistry'
    condition: 'platform-api-addressvalidation-svc.enabled'
    tags:
      - 'platform-api-addressvalidation-svc'
    enabled: true
    import-values: [] # (optional)
    alias: 'platform-api-addressvalidation-svc'
  - name: 'br-eclypse-relay-api'
    version: '>= 0.0.0-0 < 0.1-0'
    repository: '@brdevregistry'
    condition: 'br-eclypse-relay-api.enabled'
    tags:
      - 'br-eclypse-relay-api'
    enabled: true
    import-values: [] # (optional)
    alias: 'br-eclypse-relay-api'

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 'r0.3.33-brdev'

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.3.33-brdev
